services:
  dev-aws:
    image: floci/floci:latest
    container_name: floci-local
    ports:
      - "4566:4566"
    environment:
      - FLOCI_HOSTNAME=dev-aws

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    hostname: postgres-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
  
  redis:
    image: redis:7.4-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    #volumes:
    #  - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning #--requirepass your_secure_password
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
#  redis_data: