services:
  dev-aws:
    image: floci/floci:latest
    container_name: floci-local
    ports:
      - "4566:4566"
    environment:
      - FLOCI_HOSTNAME=dev-aws

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    hostname: postgres-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
  
  redis:
    image: redis:7.4-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    #volumes:
    #   - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning #--requirepass your_secure_password
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000" # Accederás desde http://localhost:4000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring
      - default # <-- Conectado a la red default
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      # Usamos la ruta absoluta real para romper el bloqueo de la ruta relativa
      - /home/pipe/proyectos/portfolio/grafana/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3200:3200"
    networks:
      - monitoring
      - default

volumes:
  postgres_data:
#  redis_data:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge